# Generated by Django 2.0.7 on 2018-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.IntegerField()),
                ('questionID', models.IntegerField()),
                ('dialogueIndex', models.IntegerField()),
            ],
        ),
    ]
