# Generated by Django 2.1 on 2018-12-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iirtech', '0002_filename_vocablist'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='topic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
